return {
  "duu261/duke.nvim",
  version = "*",
  main = "duke",
  cmd = {
    "Duke",
    "DukeNew",
    "DukeMaven",
    "DukeGradle",
    "DukeSpring",
    "DukeModule",
    "DukeAdd",
    "DukeUpgrade",
    "DukeBootUpgrade",
    "DukeOutdated",
    "DukeRemove",
    "DukeInfo",
    "DukeClearCache",
    "DukeLog",
    "DukeHealth",
  },
  opts = {},
}
